# Generated by Django 2.2.7 on 2019-11-09 12:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('Thumbnail', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('Name', models.CharField(max_length=264, null=True)),
                ('VideoId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('Duration', models.IntegerField(null=True)),
                ('Status', models.CharField(max_length=264, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264, null=True)),
                ('Description', models.TextField(blank=True)),
                ('Tags', models.CharField(blank=True, max_length=264)),
                ('Categories', models.CharField(blank=True, max_length=264)),
                ('ReferenceID', models.CharField(blank=True, max_length=264)),
                ('Video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.VideoModel')),
            ],
        ),
    ]
