# Generated by Django 2.2.7 on 2019-11-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videometa',
            name='Name',
        ),
    ]
