# Generated by Django 2.2.7 on 2019-11-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_videometa_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometa',
            name='Name',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
