# Generated by Django 2.2.7 on 2019-11-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_videometa_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videomodel',
            options={'ordering': ['Created_on', 'Duration']},
        ),
    ]
